---
- hosts: defaults
  remote_user: master
  become: true
  become_user: root

  tasks:
    - name: Inserting content in a file

      blockinfile:
        
        path: ~/Welcome/test.txt
        backup: yes
        block: |
          This is the first line
          This is the second line
